openapi: 3.1.0
info:
  version: 1.0.0
  title: SMAT Open API Documentation
  termsOfService: 'https://example.com/terms/'
  contact:
    url: 'https://www.smat.io'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  # description:
    # $ref: ./info-description.md
tags:
  - name: Wealth Manager
    description: Wealth manager specifications.
  - name: Transaction
    description: Transaction specifications.
  - name: Token
    description: Token specifications.
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'
paths:
  /crypto/wealth_manager/create_address:
    $ref: paths/crypto@wealth_manager@create_address.yaml
  /crypto/wealth_managers/aum:
    $ref: paths/crypto@wealth_managers@aum.yaml
  /crypto/wealth_managers/aggregated_assets:
    $ref: paths/crypto@wealth_managers@aggregated_assets.yaml
  /crypto/transactions/status:
    $ref: paths/crypto@transactions@status.yaml
  /crypto/transactions/hex:
    $ref: paths/crypto@transactions@hex.yaml
  /crypto/transactions/types:
    $ref: paths/crypto@transactions@types.yaml
  /crypto/transactions/onramp:
    $ref: paths/crypto@transactions@onramp.yaml
  /crypto/transactions/offramp:
    $ref: paths/crypto@transactions@offramp.yaml
  /crypto/transactions/swap:
    $ref: paths/crypto@transactions@swap.yaml
  /crypto/transactions/staking:
    $ref: paths/crypto@transactions@staking.yaml
  /crypto/tokens/price:
    $ref: paths/crypto@tokens@price.yaml
  /crypto/token/details:
    $ref: paths/crypto@token@details.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
